//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardIdleRemastered.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardIdleRemastered.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add game to time idle list.
        /// </summary>
        public static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Sync.
        /// </summary>
        public static string AllowSync {
            get {
                return ResourceManager.GetString("AllowSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Avatar {
            get {
                object obj = ResourceManager.GetObject("Avatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string BadgeProgress {
            get {
                return ResourceManager.GetString("BadgeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Black List.
        /// </summary>
        public static string BadgeProperty_Blacklisted {
            get {
                return ResourceManager.GetString("BadgeProperty_Blacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueued.
        /// </summary>
        public static string BadgeProperty_Enqueued {
            get {
                return ResourceManager.GetString("BadgeProperty_Enqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Trial Period.
        /// </summary>
        public static string BadgeProperty_HasTrial {
            get {
                return ResourceManager.GetString("BadgeProperty_HasTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string BadgeProperty_Running {
            get {
                return ResourceManager.GetString("BadgeProperty_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string BadgesHeader {
            get {
                return ResourceManager.GetString("BadgesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black List.
        /// </summary>
        public static string Blacklist {
            get {
                return ResourceManager.GetString("Blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        public static string Bookmark {
            get {
                return ResourceManager.GetString("Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Url.
        /// </summary>
        public static string CfgCustomBackground {
            get {
                return ResourceManager.GetString("CfgCustomBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Idle Process Count.
        /// </summary>
        public static string CfgIdleProcessCount {
            get {
                return ResourceManager.GetString("CfgIdleProcessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Period.
        /// </summary>
        public static string CfgIdleTrialPeriod {
            get {
                return ResourceManager.GetString("CfgIdleTrialPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string CfgOperationsHeader {
            get {
                return ResourceManager.GetString("CfgOperationsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette.
        /// </summary>
        public static string CfgPalette {
            get {
                return ResourceManager.GetString("CfgPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic Switch Repeat Count.
        /// </summary>
        public static string CfgPeriodicSwitchRepeatCount {
            get {
                return ResourceManager.GetString("CfgPeriodicSwitchRepeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Icon in TaskBar.
        /// </summary>
        public static string CfgShowInTaskBar {
            get {
                return ResourceManager.GetString("CfgShowInTaskBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Interval.
        /// </summary>
        public static string CfgSwitchInterval {
            get {
                return ResourceManager.GetString("CfgSwitchInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Settings.
        /// </summary>
        public static string CfgVisualSettings {
            get {
                return ResourceManager.GetString("CfgVisualSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dequeue Selected.
        /// </summary>
        public static string DequeueAll {
            get {
                return ResourceManager.GetString("DequeueAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dequeue.
        /// </summary>
        public static string DequeueHeader {
            get {
                return ResourceManager.GetString("DequeueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from GitHub.
        /// </summary>
        public static string DownloadRelease {
            get {
                return ResourceManager.GetString("DownloadRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Headers.
        /// </summary>
        public static string DynGridHeaders {
            get {
                return ResourceManager.GetString("DynGridHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Buttons.
        /// </summary>
        public static string DynIdleButtons {
            get {
                return ResourceManager.GetString("DynIdleButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Border.
        /// </summary>
        public static string DynLevelBorder {
            get {
                return ResourceManager.GetString("DynLevelBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runnging Game.
        /// </summary>
        public static string DynRunningGame {
            get {
                return ResourceManager.GetString("DynRunningGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats Headers.
        /// </summary>
        public static string DynStatsHeaders {
            get {
                return ResourceManager.GetString("DynStatsHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats Values.
        /// </summary>
        public static string DynStatsValues {
            get {
                return ResourceManager.GetString("DynStatsValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue Selected (Bottom).
        /// </summary>
        public static string EnqueueBottom {
            get {
                return ResourceManager.GetString("EnqueueBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue (First).
        /// </summary>
        public static string EnqueueFirst {
            get {
                return ResourceManager.GetString("EnqueueFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue (Last).
        /// </summary>
        public static string EnqueueLast {
            get {
                return ResourceManager.GetString("EnqueueLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue Selected (Top).
        /// </summary>
        public static string EnqueueTop {
            get {
                return ResourceManager.GetString("EnqueueTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter store page URL or game ID.
        /// </summary>
        public static string GameSelectionLabel {
            get {
                return ResourceManager.GetString("GameSelectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a game to idle.
        /// </summary>
        public static string GameSelectionTitle {
            get {
                return ResourceManager.GetString("GameSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games running: {0}.
        /// </summary>
        public static string GamesRunning {
            get {
                return ResourceManager.GetString("GamesRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string IdleMode_All {
            get {
                return ResourceManager.GetString("IdleMode_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One By One.
        /// </summary>
        public static string IdleMode_OneByOne {
            get {
                return ResourceManager.GetString("IdleMode_OneByOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periodic Switch.
        /// </summary>
        public static string IdleMode_PeriodicSwitch {
            get {
                return ResourceManager.GetString("IdleMode_PeriodicSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial First.
        /// </summary>
        public static string IdleMode_TrialFirst {
            get {
                return ResourceManager.GetString("IdleMode_TrialFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Last.
        /// </summary>
        public static string IdleMode_TrialLast {
            get {
                return ResourceManager.GetString("IdleMode_TrialLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Border.
        /// </summary>
        public static string LevelBorder {
            get {
                return ResourceManager.GetString("LevelBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (login).
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (logout).
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New release available.
        /// </summary>
        public static string NewRelease {
            get {
                return ResourceManager.GetString("NewRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string NextSync {
            get {
                return ResourceManager.GetString("NextSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to Steam.
        /// </summary>
        public static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in game.
        /// </summary>
        public static string NotInGame {
            get {
                return ResourceManager.GetString("NotInGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority (Higher).
        /// </summary>
        public static string PriorityHigher {
            get {
                return ResourceManager.GetString("PriorityHigher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority (Lower).
        /// </summary>
        public static string PriorityLower {
            get {
                return ResourceManager.GetString("PriorityLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string QueueHeader {
            get {
                return ResourceManager.GetString("QueueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove game from time idle list.
        /// </summary>
        public static string RemoveGame {
            get {
                return ResourceManager.GetString("RemoveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarked.
        /// </summary>
        public static string ShowcaseProperty_Bookmarked {
            get {
                return ResourceManager.GetString("ShowcaseProperty_Bookmarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collected.
        /// </summary>
        public static string ShowcaseProperty_Collected {
            get {
                return ResourceManager.GetString("ShowcaseProperty_Collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string ShowcaseProperty_Completed {
            get {
                return ResourceManager.GetString("ShowcaseProperty_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showcases.
        /// </summary>
        public static string Showcases {
            get {
                return ResourceManager.GetString("Showcases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string SteamLevel {
            get {
                return ResourceManager.GetString("SteamLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Steam.
        /// </summary>
        public static string SteamLogin {
            get {
                return ResourceManager.GetString("SteamLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload badges.
        /// </summary>
        public static string SyncBadges {
            get {
                return ResourceManager.GetString("SyncBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Idle.
        /// </summary>
        public static string TimeIdleHeader {
            get {
                return ResourceManager.GetString("TimeIdleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Idle v{0}.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle Mode.
        /// </summary>
        public static string ToolIdleMode {
            get {
                return ResourceManager.GetString("ToolIdleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ToolSearch {
            get {
                return ResourceManager.GetString("ToolSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find games by name.
        /// </summary>
        public static string ToolSearchHint {
            get {
                return ResourceManager.GetString("ToolSearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string ToolShow {
            get {
                return ResourceManager.GetString("ToolShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string TotalCards {
            get {
                return ResourceManager.GetString("TotalCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string TotalGames {
            get {
                return ResourceManager.GetString("TotalGames", resourceCulture);
            }
        }
    }
}
